# Defining spider to scrape India election data 
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import json
import scrapy
import scrapyjs
from india_election_data.items import IndiaElectionDataItem

class AssemblySpider(scrapy.Spider):
	name = "assembly"
	start_urls = [
		"http://www.indiavotes.com/ac/info?stateac=27&eid=205",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=176",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=148",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=116",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=86",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=64",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=50",
		"http://www.indiavotes.com/ac/info?stateac=27&eid=20",
		"http://www.indiavotes.com/ac/info?stateac=62&eid=235",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=236",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=207",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=179",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=146",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=120",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=94",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=54",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=27",
		"http://www.indiavotes.com/ac/info?stateac=41&eid=24",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=216",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=184",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=155",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=129",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=103",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=62",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=48",
		"http://www.indiavotes.com/ac/info?stateac=1&eid=21",
		"http://www.indiavotes.com/ac/info?stateac=2&eid=122",
		"http://www.indiavotes.com/ac/info?stateac=2&eid=96",
		"http://www.indiavotes.com/ac/info?stateac=2&eid=58",
		"http://www.indiavotes.com/ac/info?stateac=2&eid=38",
		"http://www.indiavotes.com/ac/info?stateac=2&eid=17",
		"http://www.indiavotes.com/ac/info?stateac=58&eid=212",
		"http://www.indiavotes.com/ac/info?stateac=58&eid=228",
		"http://www.indiavotes.com/ac/info?stateac=58&eid=181",
		"http://www.indiavotes.com/ac/info?stateac=58&eid=151",
		"http://www.indiavotes.com/ac/info?stateac=54&eid=233",
		"http://www.indiavotes.com/ac/info?stateac=54&eid=198",
		"http://www.indiavotes.com/ac/info?stateac=54&eid=170",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=244 ",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=230",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=201",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=169",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=134",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=113",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=52",
		"http://www.indiavotes.com/ac/info?stateac=57&eid=11",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=218",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=194",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=158",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=147",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=118",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=85",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=55",
		"http://www.indiavotes.com/ac/info?stateac=51&eid=6",
		"http://www.indiavotes.com/ac/info?stateac=37&eid=31",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=223",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=190",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=162",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=139",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=123",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=90",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=70",
		"http://www.indiavotes.com/ac/info?stateac=29&eid=29",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=240",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=210",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=182",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=152",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=125",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=101",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=75",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=43",
		"http://www.indiavotes.com/ac/info?stateac=31&eid=2",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=224",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=189",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=167",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=140",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=109",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=89",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=59",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=41",
		"http://www.indiavotes.com/ac/info?stateac=22&eid=16",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=242",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=197",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=161",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=130",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=72",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=46",
		"http://www.indiavotes.com/ac/info?stateac=32&eid=5",
		"http://www.indiavotes.com/ac/info?stateac=53&eid=243",
		"http://www.indiavotes.com/ac/info?stateac=53&eid=209",
		"http://www.indiavotes.com/ac/info?stateac=53&eid=180",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=229",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=200",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=175",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=143",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=117",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=83",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=65",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=47",
		"http://www.indiavotes.com/ac/info?stateac=43&eid=22",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=213",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=183",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=157",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=127",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=102",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=73",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=45",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=35",
		"http://www.indiavotes.com/ac/info?stateac=28&eid=7",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=136",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=111",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=91",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=63",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=39",
		"http://www.indiavotes.com/ac/info?stateac=4&eid=4",
		"http://www.indiavotes.com/ac/info?stateac=59&eid=232",
		"http://www.indiavotes.com/ac/info?stateac=59&eid=204",
		"http://www.indiavotes.com/ac/info?stateac=59&eid=172",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=241",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=206",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=177",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=144",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=119",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=93",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=68",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=36",
		"http://www.indiavotes.com/ac/info?stateac=30&eid=18",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=219",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=193",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=159",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=149",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=124",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=97",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=57",
		"http://www.indiavotes.com/ac/info?stateac=24&eid=34",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=225",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=203",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=171",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=141",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=107",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=79",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=49",
		"http://www.indiavotes.com/ac/info?stateac=44&eid=23",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=234",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=199",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=173",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=137",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=110",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=84",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=74",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=56",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=25",
		"http://www.indiavotes.com/ac/info?stateac=45&eid=19",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=226",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=195",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=166",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=135",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=114",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=82",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=76",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=44",
		"http://www.indiavotes.com/ac/info?stateac=33&eid=8",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=237",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=208",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=174",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=150",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=121",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=92",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=69",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=28",
		"http://www.indiavotes.com/ac/info?stateac=6&eid=15",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=214",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=186",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=156",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=126",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=104",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=95",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=60",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=37",
		"http://www.indiavotes.com/ac/info?stateac=39&eid=9",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=221",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=188",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=164",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=133",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=105",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=61",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=40",
		"http://www.indiavotes.com/ac/info?stateac=7&eid=14",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=231",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=202",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=165",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=142",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=106",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=88",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=66",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=32",
		"http://www.indiavotes.com/ac/info?stateac=14&eid=3",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=238",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=211",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=178",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=145",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=115",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=87",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=67",
		"http://www.indiavotes.com/ac/info?stateac=46&eid=26",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=215",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=187",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=153",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=131",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=98",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=81",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=53",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=33",
		"http://www.indiavotes.com/ac/info?stateac=40&eid=12",
		"http://www.indiavotes.com/ac/info?stateac=61&eid=239",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=227",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=196",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=168",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=138",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=112",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=78",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=51",
		"http://www.indiavotes.com/ac/info?stateac=25&eid=1",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=128",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=108",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=100",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=80",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=71",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=30",
		"http://www.indiavotes.com/ac/info?stateac=8&eid=10",
		"http://www.indiavotes.com/ac/info?stateac=60&eid=220",
		"http://www.indiavotes.com/ac/info?stateac=60&eid=191",
		"http://www.indiavotes.com/ac/info?stateac=60&eid=163",
		"http://www.indiavotes.com/ac/info?stateac=56&eid=222",
		"http://www.indiavotes.com/ac/info?stateac=56&eid=192",
		"http://www.indiavotes.com/ac/info?stateac=56&eid=160",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=217",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=185",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=154",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=132",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=99",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=77",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=42",
		"http://www.indiavotes.com/ac/info?stateac=9&eid=13"
	]

	def start_requests(self):
		for url in self.start_urls:
			yield scrapy.Request(url, self.parse,meta={
				'splash': {
					'endpoint': 'render.html',
					'args': {'wait': 0.5}
				}
			})
	
	def parse(self, response):
		item = IndiaElectionDataItem()
		item['constituency_name'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[2]/a/text()').extract()
		item['constituency_number'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[3]/text()').extract()
		item['reservation'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[4]/text()').extract()
		item['district_name'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[5]/a/text()').extract()
		item['winning_candidate'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[6]/text()').extract()
		item['winning_party'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[7]/a/text()').extract()
		item['total_electors'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[8]/text()').extract()
		item['total_votes'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[9]/text()').extract()
		item['total_votes_perc'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[10]/text()').extract()
		item['victory_margin'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[11]/text()').extract()
		item['victory_margin_perc'] = response.xpath('//*[@id="DataTables_Table_0"]/tbody/tr[*]/td[12]/a/text()').extract()
		item['state_name'] = response.xpath('//*[@id="mianContent"]/h2[1]/span/text()').extract()
		item['election_year'] = response.xpath('//*[@id="mianContent"]/h2[1]/text()[2]').extract()
		yield item

